Feature/add icon
cvicream/cv-icream pull request #184
Opened 2023-12-02 13:13 UTC by liuqadnyc

Uploading Screen Recording 2023-12-02 at 13.12.29.mov…

2023-12-04 22:32 UTC, agnuschan commented
I noticed that in some of the preset boxes, the icons are not aligned with the social network name

![CleanShot 2023-12-04 at 21 45 23@2x](https://github.com/cvicream/cv-icream/assets/30631048/4f5fb882-eac1-4c9f-813d-79277193ed38)
![CleanShot 2023-12-04 at 21 46 09@2x](https://github.com/cvicream/cv-icream/assets/30631048/69dc0984-e4c4-4a38-af3c-a2fbe198dd81)

When I go to Product Manager or custom template, there is only one example there, so this is not aligned with other roles
![CleanShot 2023-12-04 at 21 46 43@2x](https://github.com/cvicream/cv-icream/assets/30631048/bc6a7ca0-1e10-45a3-b6e0-3bb41f86e934)

So what I am thinking is, since we may not provide the template by role anymore (we may be based on the experience, right?), probably we only default the one example there, I mean only LinkedIn that one, what do you think?

2023-12-05 09:11 UTC, liuqadnyc commented
> I noticed that in some of the preset boxes, the icons are not aligned with the social network name
> 
> ![CleanShot 2023-12-04 at 21 45 23@2x](https://private-user-images.githubusercontent.com/30631048/287854701-4f5fb882-eac1-4c9f-813d-79277193ed38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjcxMjEsIm5iZiI6MTcwMTc2NjgyMSwicGF0aCI6Ii8zMDYzMTA0OC8yODc4NTQ3MDEtNGY1ZmI4ODItZWFjMS00YzlmLTgxM2QtNzkyNzcxOTNlZDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5MDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYjcxNThlMTQzZWU5YTZlNzllNWRmNTY5OGJmZTBiNzJkNWNiMDAyZWE1YTRlZmYyNzVhMDE2NzdmODNmYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yhegE9XVJg5EKURa7uC0xP0-T43UzFsnoB3DzFMmr20) ![CleanShot 2023-12-04 at 21 46 09@2x](https://private-user-images.githubusercontent.com/30631048/287854741-69dc0984-e4c4-4a38-af3c-a2fbe198dd81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjcxMjEsIm5iZiI6MTcwMTc2NjgyMSwicGF0aCI6Ii8zMDYzMTA0OC8yODc4NTQ3NDEtNjlkYzA5ODQtZTRjNC00YTM4LWFmM2MtYTJmYmUxOThkZDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5MDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYjljMWZkYTRhZTU0OTVlNWU3ZGZlZGE2YmJiZDZmMzdjYmFhYzA1ZGVhY2Q0MmMwNTNhMTNjZTI3MmQ5MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EVVlG_FzXVLUCg_9Z6RDxqjVe0fwp1axajwOuzbx-JU)
> 
> When I go to Product Manager or custom template, there is only one example there, so this is not aligned with other roles ![CleanShot 2023-12-04 at 21 46 43@2x](https://private-user-images.githubusercontent.com/30631048/287854968-bc6a7ca0-1e10-45a3-b6e0-3bb41f86e934.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjcxMjEsIm5iZiI6MTcwMTc2NjgyMSwicGF0aCI6Ii8zMDYzMTA0OC8yODc4NTQ5NjgtYmM2YTdjYTAtMWUxMC00NWEzLWI2ZTAtM2JiNDFmODZlOTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5MDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkOTc2YzBjMDhiZjNkMTcxMzE4ZjNkYjRjOGEyYWQ3ODg4ZGU3Yjk2NDlhM2I5NDg5ODY2NTE3NTNlMjFlMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._JUIfRPn1dS4TvpU-9xhtaaY1zux-AxVLBDcxSGd5RA)
> 
> So what I am thinking is, since we may not provide the template by role anymore (we may be based on the experience, right?), probably we only default the one example there, I mean only LinkedIn that one, what do you think?

Nice found! The reason is I didn't put default value instead if there is no icon I use linkedin one, so either I can put default value or like you said make them all the same.

2023-12-05 16:34 UTC, AmberYYH commented
https://github.com/cvicream/cv-icream/assets/143964615/7dbede09-8dac-4d2d-8e70-504cdb512dbd

我發現手指跟箭頭都可以展開icons，如果都可以的話只留一個箭頭就好？

2023-12-05 16:41 UTC, Shan-29 commented
關於 Icon 那一格，以及下拉選單的UI呈現方式我有做了一些調整，主要是因為：
1. Icon 那一格：因為只有一個 icon 但佔了一整行，所以覺得好像有點浪費空間，所以把這邊調整跟 Title 部分在同一行
2. 下拉選單：每一個 icon 間的距離調近（符合我們現在 Design System 的常用 spacing）
3. 其他一些關於 Status 的轉換，和響應式的呈現方式，我也有做了比較詳細的 UI

如果有問題，或是不好做的部分，再請提出了，感謝！

<img width="1230" alt="Screenshot 2023-12-05 at 17 36 17" src="https://github.com/cvicream/cv-icream/assets/68609691/5df22c22-6680-40d5-8b23-ecd63ab807ea">

2023-12-12 12:35 UTC, Shan-29 commented
Remove icon UI

<img width="837" alt="Screenshot 2023-12-12 at 13 34 47" src="https://github.com/cvicream/cv-icream/assets/68609691/ca20518e-c95a-48ed-800f-76d26ad7121e">


Hover 的時候變成 70%-black

<img width="815" alt="Screenshot 2023-12-12 at 13 34 52" src="https://github.com/cvicream/cv-icream/assets/68609691/47aeca75-5d19-4c0e-bfe4-b636306bd12e">

2023-12-12 12:38 UTC, Shan-29 commented
因為剛剛看UI一直覺得Padding有點不均勻，所以我把左右也調整16px~再麻煩Zack協助調整，感謝！

<img width="754" alt="Screenshot 2023-12-12 at 13 36 44" src="https://github.com/cvicream/cv-icream/assets/68609691/35d98b04-7367-4724-83fe-e336b411ba63">

2023-12-12 16:06 UTC, liuqadnyc commented
@agnuschan we decide to not show the icon at first and let users add themselves

2023-12-13 11:51 UTC, Shan-29 commented
這邊的Icon和字體麻煩協助置中～

<img width="514" alt="Screenshot 2023-12-13 at 12 45 06" src="https://github.com/cvicream/cv-icream/assets/68609691/790ab357-b55a-42ff-8c42-c2b21af2836c">

2023-12-13 12:03 UTC, Shan-29 commented
響應式 -

Side bar比較小的時候：
1. "Remove Icon"請也置右
2. 請把選Icon的小Box調整在橘色框框內（跟左邊邊緣一樣的對齊方式）

感謝！

<img width="529" alt="Screenshot 2023-12-13 at 12 47 48" src="https://github.com/cvicream/cv-icream/assets/68609691/d688fcc5-491f-41e5-a4b2-70b691b4c594">

2023-12-13 12:04 UTC, Shan-29 commented
Social Media這區因為有放Link的區域了，想說如果不影響這個component的話，可以在Title這邊的文字編輯器隱藏Link這個選項，避免使用者困惑，感謝！

<img width="1004" alt="Screenshot 2023-12-13 at 12 42 30" src="https://github.com/cvicream/cv-icream/assets/68609691/b8fac320-a2ae-4bf2-aaeb-80d92d9f91aa">

2023-12-13 12:11 UTC, Shan-29 commented
Title的文字編輯的縮排在Preview上沒有反應

https://github.com/cvicream/cv-icream/assets/68609691/1561ff4f-1b03-42ce-a8ad-f677058c04f4

2023-12-13 12:12 UTC, Shan-29 commented
Title的文字編輯的列點功能在Preview上沒有反應

https://github.com/cvicream/cv-icream/assets/68609691/3b334a1e-8bae-4b59-a4d7-1205201160c8

2023-12-13 12:13 UTC, Shan-29 commented
麻煩協助加上Icon們的hovering UI（跟focus的UI一樣）

https://github.com/cvicream/cv-icream/assets/68609691/55ac6a23-b89e-41ec-91ca-37cce4b59e13

2023-12-13 12:14 UTC, Shan-29 commented
拿掉Link後，還是可以點選（會直接連到我們的編輯器）

https://github.com/cvicream/cv-icream/assets/68609691/162bf872-75a5-40b0-9fe6-e2cb45dc3e45

2023-12-13 17:23 UTC, liuqadnyc commented
> 這邊的Icon和字體麻煩協助置中～
> 
>

我看是好的欸 
![Screenshot 2023-12-13 at 17 23 25](https://github.com/cvicream/cv-icream/assets/34543459/18ab3603-caf8-4b4c-b449-8708a23b28a1)

2023-12-13 17:27 UTC, liuqadnyc commented
> 拿掉Link後，還是可以點選（會直接連到我們的編輯器）
> 
>  Screen.Recording.2023-12-13.at.12.45.28.mov

這之前就有的問題，我可以看看怎麼回事

2023-12-15 15:32 UTC, liuqadnyc commented
> 響應式 -
> 
> Side bar比較小的時候：
> 
> 1. "Remove Icon"請也置右
> 2. 請把選Icon的小Box調整在橘色框框內（跟左邊邊緣一樣的對齊方式）
> 
> 感謝！
> 
> <img alt="Screenshot 2023-12-13 at 12 47 48" width="529" src="https://private-user-images.githubusercontent.com/68609691/290182794-d688fcc5-491f-41e5-a4b2-70b691b4c594.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTI5NDIsIm5iZiI6MTcwMjY1MjY0MiwicGF0aCI6Ii82ODYwOTY5MS8yOTAxODI3OTQtZDY4OGZjYzUtNDkxZi00MWU1LWE0YjItNzBiNjkxYjRjNTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE1MDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMWVmM2NhZDBjMGNiODhkYTA2MjJkYTg4YjVmOTk4MTkyMmZmMGQ3MDM5NGQ1ZTRmMWI3NTljM2EyOTA1ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n8Rwi4cif5z8JGU5AWnNJkRs_oOOtfqON4XivGyUaY8">

如果縮小的話就要scroll bar吧，那這樣下面的字你要讓他靠最右嗎，這樣一開始會看不到，還是換成靠左？

2023-12-17 23:17 UTC, dodosoya commented
@liuqadnyc 當螢幕寬度小時 icon 的 pop-up 會超出去，再麻煩看一下。

![image](https://github.com/cvicream/cv-icream/assets/16853417/a200655d-35db-4d53-951d-50c32998d240)

2023-12-17 23:20 UTC, dodosoya requested changes

2023-12-17 23:20 UTC, dodosoya commented on src/components/IconEditor.vue
> +import { DEFAULT_TEMPLATE, SOCIAL_MEDIA_ICONS } from '~/constants'
DEFAULT_TEMPLATE 好像可以移除，沒有看到在這個檔案被使用。

2023-12-18 08:43 UTC, Shan-29 commented
> > 這邊的Icon和字體麻煩協助置中～
> 
> 我看是好的欸 ，請問要怎麼重現？ ![Screenshot 2023-12-13 at 17 23 25](https://private-user-images.githubusercontent.com/34543459/290275796-18ab3603-caf8-4b4c-b449-8708a23b28a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODgzMjQsIm5iZiI6MTcwMjg4ODAyNCwicGF0aCI6Ii8zNDU0MzQ1OS8yOTAyNzU3OTYtMThhYjM2MDMtY2FmOC00YjRjLWI0NDktODcwOGEyM2IyOGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA4MjcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNGM1MjAxZGFmMzgyMDIxOGQ0MmUxZWYwNGUxZjMxNzg2MTQ2ZjlkOGFmMDVkMmMzZDZlMDY4OGNmZmM4NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aPJaG5HHaEgavi5GjsctTBTpI_laLCWIOTkLr8JPvlU)

我的瀏覽器是Chrome (Mac)，跟你用的一樣嗎？

2023-12-19 21:56 UTC, dodosoya commented
@liuqadnyc 看到另一個現象，當 icon 列可以滾動時，下面 Remove Icon 按鈕也會跟著移動，不確定原來設計是不是這樣，可以麻煩確認一下嗎？

https://github.com/cvicream/cv-icream/assets/16853417/62f67217-0291-4a42-9908-bdd774fe7a23

2023-12-20 16:07 UTC, Shan-29 commented
> @liuqadnyc 看到另一個現象，當 icon 列可以滾動時，下面 Remove Icon 按鈕也會跟著移動，不確定原來設計是不是這樣，可以麻煩確認一下嗎？
> 
>  CV.Icream.mp4

@liuqadnyc 我覺得這邊如果可以調整成只有上面的Icon可以滑動，下面的"Remove Icon"直接固定置右，這樣應該整個體驗會更直覺？

2023-12-21 21:51 UTC, dodosoya approved these changes
Looks good to me 👍

2023-12-22 00:13 UTC, merged